{
    "label": "unknown",
    "execution_time": 8184.920907497406,
    "error": "Traceback (most recent call last):\n  File \"/4tb/dowon/PRISM_evaluation/scripts/patchsim.py\", line 254, in run\n    self.parse_trace()\n  File \"/4tb/dowon/PRISM_evaluation/scripts/patchsim.py\", line 227, in parse_trace\n    subprocess.run(f\"make parse ARGS=\\\"'{failing_tests_str}' '{self.trace_log_dir}' '{self.patch.patch_path}' '{self.parse_out_dir}'\\\"\", shell=True, timeout=3600, capture_output=True, cwd=PATCHSIM_HOME)\n  File \"/usr/lib/python3.12/subprocess.py\", line 550, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/subprocess.py\", line 1209, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/subprocess.py\", line 2116, in _communicate\n    self._check_timeout(endtime, orig_timeout, stdout, stderr)\n  File \"/usr/lib/python3.12/subprocess.py\", line 1253, in _check_timeout\n    raise TimeoutExpired(\nsubprocess.TimeoutExpired: Command 'make parse ARGS=\"'org.apache.commons.math3.optimization.direct.CMAESOptimizerTest::testFitAccuracyDependsOnBoundary' '/4tb/dowon/PRISM_evaluation/results/Math18b/1a1a4bfa/patchsim/traces' '/4tb/dowon/PRISM_evaluation/benchmarks/rq2/EMSE21/Dunassessed/Cardumen/Math/Math-18-patch3-Cardumen-incorrect-EMSE21.patch' '/4tb/dowon/PRISM_evaluation/results/Math18b/1a1a4bfa/patchsim/parsed'\"' timed out after 3600 seconds\n"
}